// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/explorer/v1/explorer.proto

// Protobuf Java Version: 3.25.2
package com.explorer.v1;

public interface ExplorerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:explorer.v1.ExplorerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
