// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/explorer/v1/explorer.proto

// Protobuf Java Version: 3.25.2
package com.explorer.v1;

public interface ExplorerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:explorer.v1.ExplorerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
